# Generated by Django 5.0.2 on 2024-03-10 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(default=0, verbose_name='میانگین امتیاز'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='score',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='امتیاز'),
            preserve_default=False,
        ),
    ]
