# Generated by Django 5.0.2 on 2024-03-10 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_product_avg_rating_productcomment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='score',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='امتیاز'),
        ),
    ]
