# Generated by Django 5.0.2 on 2024-03-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_productcomment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_rating',
            field=models.IntegerField(default=0, verbose_name='تعداد نظر ها'),
        ),
    ]
