# Generated by Django 5.0.2 on 2024-03-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_remove_order_address_remove_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderformclass',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='نهایی شده/نشده'),
        ),
    ]
