# Generated by Django 5.0.2 on 2024-03-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_orderformclass_followup_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='ارسال شده'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_progress',
            field=models.BooleanField(default=False, verbose_name='در حال انجام'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_start',
            field=models.BooleanField(default=True, verbose_name='در حال بررسی'),
        ),
    ]
