# Generated by Django 5.0.2 on 2024-03-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0006_order_is_finish_order_is_progress_order_is_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderformclass',
            name='followup_code',
            field=models.IntegerField(blank=True, verbose_name='کد پیگیری'),
        ),
    ]
